-- ILG Database Schema
-- Engine: SQLite (MVP), migration path to PostgreSQL
-- Run via: node db/init.js

PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=ON;

-- Vertical configurations (generated by vertical-adapter skill)
CREATE TABLE IF NOT EXISTS vertical_configs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vertical_id TEXT UNIQUE NOT NULL,
    vertical_name TEXT NOT NULL,
    config_json TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Organizations discovered by org-discoverer
CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    vertical_id TEXT NOT NULL,
    name TEXT NOT NULL,
    org_type TEXT,
    website TEXT,
    state TEXT,
    city TEXT,
    size_estimate TEXT,
    industry_tags TEXT,          -- JSON array
    fit_score REAL DEFAULT 0.0,
    discovery_source TEXT,
    raw_data_json TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (vertical_id) REFERENCES vertical_configs(vertical_id)
);

-- Contacts extracted by contact-extractor
CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    org_id INTEGER NOT NULL,
    first_name TEXT,
    last_name TEXT,
    title TEXT,
    email TEXT,
    linkedin_url TEXT,
    role_category TEXT,          -- maps to contact_targeting role priority
    is_decision_maker BOOLEAN DEFAULT 0,
    profile_data_json TEXT,      -- cached LinkedIn/web profile data
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    enriched_at DATETIME,
    FOREIGN KEY (org_id) REFERENCES organizations(id)
);

-- Raw and analyzed social media signals
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contact_id INTEGER,          -- nullable: some signals are org-level
    org_id INTEGER,
    vertical_id TEXT NOT NULL,
    source_platform TEXT NOT NULL,  -- 'linkedin' | 'reddit' | 'twitter' | 'web'
    source_url TEXT,
    raw_text TEXT NOT NULL,
    signal_type TEXT,              -- from vertical's signal_taxonomy (null before analysis)
    polarity TEXT,                 -- 'positive' | 'negative' | 'neutral'
    intensity INTEGER,             -- 1-10
    relevance_score REAL,          -- 0.0-1.0
    summary TEXT,
    entity_mentions_json TEXT,
    captured_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    analyzed_at DATETIME,
    FOREIGN KEY (contact_id) REFERENCES contacts(id),
    FOREIGN KEY (org_id) REFERENCES organizations(id)
);

-- Composite lead scores
CREATE TABLE IF NOT EXISTS lead_scores (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contact_id INTEGER NOT NULL,
    vertical_id TEXT NOT NULL,
    composite_score REAL NOT NULL,
    tier TEXT NOT NULL,            -- 'HOT' | 'WARM' | 'COOL' | 'COLD'
    signal_score REAL,
    role_score REAL,
    org_fit_score REAL,
    signal_breakdown_json TEXT,    -- explainability: which signals drove the score
    scoring_model_version TEXT DEFAULT 'v1',
    scored_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);

-- Enrichment cache to prevent redundant API calls
CREATE TABLE IF NOT EXISTS enrichment_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    entity_type TEXT NOT NULL,     -- 'contact' | 'org'
    entity_id INTEGER NOT NULL,
    cache_key TEXT NOT NULL,       -- e.g. 'linkedin_profile', 'website_crawl'
    data_json TEXT NOT NULL,
    fetched_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME NOT NULL,
    UNIQUE(entity_type, entity_id, cache_key)
);

-- Outreach tracking
CREATE TABLE IF NOT EXISTS outreach_log (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    contact_id INTEGER NOT NULL,
    vertical_id TEXT NOT NULL,
    channel TEXT NOT NULL,         -- 'email' | 'linkedin' | 'phone'
    message_draft TEXT,
    status TEXT DEFAULT 'draft',   -- 'draft' | 'sent' | 'replied' | 'bounced'
    sent_at DATETIME,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (contact_id) REFERENCES contacts(id)
);

-- API usage tracking (critical for free tier limits)
CREATE TABLE IF NOT EXISTS api_usage (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    platform TEXT NOT NULL,        -- 'twitter' | 'reddit' | 'linkedin' | 'anthropic'
    endpoint TEXT,
    tokens_used INTEGER DEFAULT 0,
    requests_made INTEGER DEFAULT 1,
    cost_estimate_usd REAL DEFAULT 0.0,
    recorded_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_orgs_vertical ON organizations(vertical_id);
CREATE INDEX IF NOT EXISTS idx_contacts_org ON contacts(org_id);
CREATE INDEX IF NOT EXISTS idx_signals_contact ON signals(contact_id);
CREATE INDEX IF NOT EXISTS idx_signals_org ON signals(org_id);
CREATE INDEX IF NOT EXISTS idx_signals_vertical ON signals(vertical_id);
CREATE INDEX IF NOT EXISTS idx_signals_type ON signals(signal_type);
CREATE INDEX IF NOT EXISTS idx_lead_scores_contact ON lead_scores(contact_id);
CREATE INDEX IF NOT EXISTS idx_lead_scores_tier ON lead_scores(tier);
CREATE INDEX IF NOT EXISTS idx_cache_lookup ON enrichment_cache(entity_type, entity_id, cache_key);
CREATE INDEX IF NOT EXISTS idx_api_usage_platform ON api_usage(platform, recorded_at);
